DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS files;


CREATE TABLE users(
	username TEXT PRIMARY KEY,
	password TEXT NOT NULL,
	usercode TEXT NOT NULL
);


CREATE TABLE files(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	usercode TEXT NOT NULL,
	filename TEXT,
	file BLOB
);